version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Berlin

- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Berlin
