name: credentials
description: "Setup credentials"

inputs:
  keystoreFile:
    description: "Base64 encoded key store"
    required: false
  firebaseServiceAccount:
    description: "Firebase service account credentials"
    required: false
  playStoreServiceAccount:
    description: "Play Store service account credentials"
    required: false


runs:
  using: "composite"
  steps:
    - name: "Keystore"
      if: ${{ inputs.keyStoreFile }}
      run: |
        echo '${{ inputs.keyStoreFile }}' | base64 --decode > keystore.jks
        echo KEYSTORE_FILE=$GITHUB_WORKSPACE/keystore.jks >> $GITHUB_ENV
      shell: bash
    - name: "Firebase credentials"
      if: ${{ inputs.firebaseServiceAccount }}
      run: |
        echo '${{ inputs.firebaseServiceAccount }}' > firebase.json 
        echo GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase.json >> $GITHUB_ENV
      shell: bash
    - name: "Play store credentials"
      if: ${{ inputs.playStoreServiceAccount }}
      run: |
        echo '${{ inputs.playStoreServiceAccount }}' > playstore.json 
        echo PLAY_STORE_CREDENTIALS=$GITHUB_WORKSPACE/playstore.json >> $GITHUB_ENV
      shell: bash